name: jameda
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cartopy
  - geopandas
  - geoviews
  - holoviews
  - nltk
  - numpy
  - scikit-learn
  - hvplot
  - pandas
  - libxgboost
  - scipy
  - xgboost
  - tensorflow=2.2.0
  - seaborn
  - transformers
